import Head from 'next/head'
import BarChart from '../components/BarChart'

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Stock Exchanger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper my-12">
        <div className="container">
          <h1 className="text-3xl font-bold">Stock Exchanger</h1>
          <div className="h-50vh" id="eChart">
            <BarChart />
          </div>
        </div>
      </div>
    </div>
  )
}
