import Head from 'next/head'

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <h1 className="text-3xl font-bold">Hello world!</h1>
      </div>
    </div>
  )
}
